# Generated by Django 5.0.2 on 2024-02-26 20:35

import docker_mgmt.remotes.setup
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True)),
                ('number_of_cores', models.IntegerField(default=1)),
                ('cpu_vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu_clocks', models.CharField(blank=True, max_length=200, null=True)),
                ('memory_totals', models.IntegerField(blank=True, null=True)),
                ('disk_info', models.JSONField(default={})),
                ('roles', models.ManyToManyField(to='baremetal.ansiblerole')),
            ],
            bases=(models.Model, docker_mgmt.remotes.setup.Server),
        ),
    ]
